### ISSUE TITLE
>>>=  , etc ??

### ISSUE THREAD

**Issue by TopView** [atoponce/nodepassgen#1]
I can see what most of your code does, but please help me understand what this line does:

count >>>= 0; min = (-count >>> 0) % count;

I'm not as familiar w/ shifting in javascript.  The first part always seems to set count to zero.  (Can't find >>>= in my js docs.)

Thanks, and great tool!  Thank you very much for writing and sharing it.

**Comment by atoponce** [comment]
Sure. So, `a >>> b` is a bitwise operator that [shifts `a` in binary representation `b` (< 32) bits to the right](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Bitwise_Operators), discarding bits shifted off, and shifting in 0's from the left.

As a result `count >>>= 0` ensures that the `count` variable is a 32-bit number. If the number is any larger than 32-bits, it's 0. As an example:

    % var count = 2**31;
    % console.log(count);
    2147483648
    % count >>>= 0;
    % console.log(count);
    2147483648
    % count = 2**32+1
    % console.log(count);
    4294967297
    % count >>>= 0;
    % console.log(count);
    0

The reason this is important, is on the next line we do:

     min = (-count >>> 0) % count;

If `count` was larger than 32-bits, it's now zero. That means in the `do ... while` loop, random numbers are always generated when they're less than `min`. But if `count` is zero, then `min` is zero, and if `min` is zero, the `do ... while` loop will execute once, then exit, and we won't have a password.

So, what's the point? The point is that `window.crypto.getRandomValues()` can generate a 32-bit random number at largest via `UInt32Array`. So, I force `count` to be 32-bits. Any larger, and it's treated separately, preventing you from generating a password.

**Comment by TopView** [comment]
I think i see:  `a >>>= b`   is the same as `a = a >>> b.`  (The `>>>=` syntax was not listed in the references I first looked up, in fact I still haven't found it but I'm guessing this is what it is).  

So this means count `count >>>= 0` is the same as `count = count >>> 0`, which doesn't shift anything, but still has the side effect of either returning counts of 0-32 bits, less one, OR returning zero if count is greater than 32 bits wide.  Interesting out of bound behavior, but then I guess this function had to do something predicable when given overly large numbers.

Thanks for your clear explanation.

**Comment by atoponce** [comment]
No problem. `count >>>= 0` is indeed identical to `count = count >>> 0`. It's analogous to `i += 1`, etc. Just shorthand.
